#!/bin/bash

startdir=$(pwd)
cd $(dirname "${0}")
export BREPL_DIR=$(pwd -P)
cd $startdir

#FIXME: if you don't have $CLOJURESCRIPT_HOME set, uncommen the next line.
#export CLOJURESCRIPT_HOME=/path/to/clojurescript
BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"

rlwrap -r -c -b $BREAK_CHARS "${BREPL_DIR}/script/cljbrepl" "$startdir/src"



