#!/bin/bash

startdir=$(pwd)
cd $(dirname "${0}")
export BREPL_DIR=$(pwd -P)
cd $startdir

export CLOJURESCRIPT_HOME=/users/chris/repos/clojurescript
BREAK_CHARS="(){}[],^%$#@\"\";:''|\\"

rlwrap -r -c -b $BREAK_CHARS "${BREPL_DIR}/script/cljbrepl" "$startdir/src"



